# Generated by Django 6.0.3 on 2026-04-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants_count',
        ),
        migrations.AlterField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='EventHub.event'),
        ),
    ]
