# Generated by Django 6.0.3 on 2026-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0003_event_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default='2027-05-10T10:00:00'),
        ),
    ]
