# Generated by Django 6.0.3 on 2026-04-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventHub', '0006_event_end_date_after_start_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='end_date_after_start_date',
        ),
    ]
